package com.example.taskflow.web.mapper;

import com.example.taskflow.domain.Task;
import com.example.taskflow.web.dto.TaskResponse;

import java.util.Comparator;

/**
 * Entity ⇄ DTO conversion for tasks.
 *
 * <p>Hand-written rather than generated by MapStruct: one fewer annotation
 * processor in the build, and the mapping stays readable — which matters when
 * the point of the project is for humans and Copilot to read it.</p>
 */
public final class TaskMapper {

    private TaskMapper() {
        // static utility
    }

    /**
     * Converts an entity to its API representation, computing derived fields.
     *
     * @param task the entity, must not be {@code null}
     * @return the response DTO
     */
    public static TaskResponse toResponse(Task task) {
        return new TaskResponse(
                task.getId(),
                task.getTitle(),
                task.getDescription(),
                task.getStatus(),
                task.getPriority(),
                task.getAssignee(),
                task.getDueDate(),
                task.isOverdue(),
                task.getStatus().allowedTransitions().stream()
                        .sorted(Comparator.comparing(Enum::name))
                        .toList(),
                task.getCreatedAt(),
                task.getUpdatedAt(),
                task.getVersion());
    }
}
